using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using sim.EPL;

namespace sim
{
    public partial class Category : Form
    {
        DB_SMPEntities db = new DB_SMPEntities();
        TB_CAT tb_cat=new TB_CAT();
        BL.Methods methods = new BL.Methods();
        int id;
        public Category()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            sim.DB_SMPEntities dbContext = new sim.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_CAT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_CAT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_Add_Click(object sender, EventArgs e)
        {
            PL.FFRM_CAT_ADD frm_add = new PL.FFRM_CAT_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "اضافه";
            frm_add.Show();
        }

        private void btn_delet_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {

                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show("delet operation ", "did you want the delet?", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    
                    
                    tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(tb_cat).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.txt_caption.Text = "تم حذف النص";
                    toast.Show();
                    Update_data();
                }
            }
            catch (Exception ex) {
                dialog.txt_caption.Text = "لايوجد صنف لحذفه";
                dialog.Width = this.Width;
                dialog.Show();
            }
        }

        private void Update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_CAT.ToList();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Update_data();
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            PL.FFRM_CAT_ADD frm_add = new PL.FFRM_CAT_ADD();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
            frm_add.edt_name.Text = tb_cat.CAT_NAME.ToString();
            methods.by = tb_cat.CAT_COVER;
            frm_add.pic_cover.Image = Image.FromStream(methods.convert_image());
            frm_add.id = id;
            frm_add.btn_add.Text = "تعديل";
            frm_add.Show();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_search.Text;
            gridControl1.DataSource = db.TB_CAT.Where(x => x.CAT_NAME.Contains(_search)).ToList();
        }
    }
}
