//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAT
    {
        public int ID { get; set; }
        public string CAT_NAME { get; set; }
        public byte[] CAT_COVER { get; set; }
    }
}
